//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CACAIXA
    {
        public int Id { get; protected set; }
        public string IDUSUARIO { get; set; }
        public int SQCAIXA { get; set; }
        public System.DateTime DTABERTURA { get; set; }
        public int NUFECHAMEN { get; set; }
        public System.TimeSpan HRABERTURA { get; set; }
        public Nullable<System.DateTime> DTFECHAMEN { get; set; }
        public Nullable<System.TimeSpan> HRFECHAMEN { get; set; }
        public short STCAIXA { get; set; }
        public decimal VLSALDOANT { get; set; }
        public Nullable<decimal> VLSALDOATU { get; set; }
        public double SMFIELDATU { get; set; }
        public Nullable<int> CDPDV { get; set; }
        public Nullable<int> CDLOCVENDA { get; set; }
        public int CDUOP { get; set; }
        public string LGFECHAMEN { get; set; }
        public string NMESTACAO { get; set; }
        public int CDPESSOA { get; set; }
        public Nullable<System.DateTime> DTAUTORIZ { get; set; }
        public Nullable<short> CDUNIDADE { get; set; }
        public Nullable<short> NUAUTORIZ { get; set; }
        public string TPAUTORIZ { get; set; }

        public virtual IList<PAGAMENTOS> PAGAMENTOS { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual UOP UOP { get; set; }
    }
}
