//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class COBRANCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COBRANCA()
        {
            this.PAGAMENTOS = new HashSet<PAGAMENTOS>();
        }
        public int Id { get; protected set; }
        public string IDCLASSE { get; set; }
        public string CDELEMENT { get; set; }
        public int SQCOBRANCA { get; set; }
        public int CDUOPCOB { get; set; }
        public int CDUOP { get; set; }
        public int SQMATRIC { get; set; }
        public string DSCOBRANCA { get; set; }
        public short RFCOBRANCA { get; set; }
        public decimal VLCOBRADO { get; set; }
        public System.DateTime DTVENCTO { get; set; }
        public System.DateTime DTEMISSAO { get; set; }
        public short STRECEBIDO { get; set; }
        public Nullable<short> TPCOBRANCA { get; set; }
        public Nullable<decimal> PCJUROS { get; set; }
        public System.DateTime DTATU { get; set; }
        public double SMFIELDATU { get; set; }
        public System.TimeSpan HRATU { get; set; }
        public string LGATU { get; set; }
        public string VLCARACTE1 { get; set; }
        public string VLCARACTE2 { get; set; }
        public Nullable<short> DDCOBJUROS { get; set; }
        public Nullable<short> DDINIJUROS { get; set; }
        public Nullable<decimal> PCMULTA { get; set; }
        public string DSCANCELAM { get; set; }
        public int CDUOPREC { get; set; }
        public string NMESTACAO { get; set; }
        public Nullable<int> CDCANCELA { get; set; }
        public short TPMORA { get; set; }
        public string LGCANCEL { get; set; }
        public Nullable<int> IDCOBRANCA { get; set; }
        public virtual ICollection<PAGAMENTOS> PAGAMENTOS { get; set; }
        public virtual CLIENTELA CLIENTELA { get; set; }
        public virtual UOP UOP { get; set; }
    }
}
