//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ENDERECOS
    {
        public int Id { get; protected set; }
        public string IDCLASSE { get; set; }
        public string CDELEMENT { get; set; }
        public short SQENDEREC { get; set; }
        public string DSLOGRADOU { get; set; }
        public string SIESTADO { get; set; }
        public string DSCOMPLEM { get; set; }
        public short CDMUNICIP { get; set; }
        public Nullable<int> NUIMOVEL { get; set; }
        public string DSBAIRRO { get; set; }
        public string NUCEP { get; set; }
        public short STPRINCIP { get; set; }
        public Nullable<System.DateTime> DTINICIO { get; set; }
        public System.TimeSpan HRATU { get; set; }
        public double SMFIELDATU { get; set; }
        public System.DateTime DTATU { get; set; }
        public string LGATU { get; set; }
        public Nullable<int> CDUOP { get; set; }
        public Nullable<int> SQMATRIC { get; set; }
        public Nullable<int> IDENDERECO { get; set; }
        public string DSMUNICIP { get; set; }
        public bool Equals(ENDERECOS other)
        {
            return this.IDCLASSE == other.IDCLASSE && this.SQENDEREC == other.SQENDEREC;
        }

        public override int GetHashCode()
        {
            return this.Id.GetHashCode();
        }
    }
}
