//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MUNICIPIO
    {
        public int Id { get; protected set; }
        public short CDMUNICIP { get; set; }
        public Nullable<short> CDMUNINSS { get; set; }
        public string SIESTADO { get; set; }
        public string DSMUNICIP { get; set; }
        public string DSMUNMASK { get; set; }
        public Nullable<System.DateTime> DTATU { get; set; }
        public Nullable<System.TimeSpan> HRATU { get; set; }
        public string LGATU { get; set; }
    }
}
