//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System.Collections.Generic;
    using System;

    public partial class PAGAMENTOS
    {
        public int Id { get; protected set; }
        public string IDUSUARIO { get; set; }
        public System.DateTime DTRECEBIDO { get; set; }
        public int SQCAIXA { get; set; }
        public System.TimeSpan HRRECEBIDO { get; set; }
        public int CDMOEDAPGT { get; set; }
        public int SQPAGAMENT { get; set; }
        public string IDCLASSE { get; set; }
        public string CDELEMENT { get; set; }
        public int SQCOBRANCA { get; set; }
        public decimal VLRECEBIDO { get; set; }
        public Nullable<decimal> VLJUROS { get; set; }
        public double SMFIELDATU { get; set; }
        public short STCANCELAD { get; set; }
        public string DSCANCELAD { get; set; }
        public Nullable<decimal> VLACRESCIM { get; set; }
        public Nullable<decimal> VLDESCONTO { get; set; }
        public short NUIMPVIA2 { get; set; }
        public int CDUOPPGTO { get; set; }
        public Nullable<int> SQVENDA { get; set; }
        public string LGCANCEL { get; set; }
        public Nullable<System.DateTime> DTCANCEL { get; set; }
        public Nullable<System.TimeSpan> HRCANCEL { get; set; }
        public string NMESTACAO { get; set; }
        public int CDPESSOA { get; set; }
        public Nullable<int> IDCOBRANCA { get; set; }

        public virtual COBRANCA COBRANCA { get; set; }
        public virtual CACAIXA CACAIXA { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual PagamentoCielo PagamentoCielo { get; set; }
    }
}