//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESSOA()
        {
            this.CACAIXA = new HashSet<CACAIXA>();
            this.PAGAMENTOS = new HashSet<PAGAMENTOS>();
        }

        public int Id { get; protected set; }
        public Nullable<short> CDADMIN { get; set; }
        public string NMPESSOA { get; set; }
        public int CDPESSOA { get; set; }
        public Nullable<System.DateTime> DTCADASTRO { get; set; }
        public System.DateTime DTATU { get; set; }
        public System.TimeSpan HRATU { get; set; }
        public short TPPESSOA { get; set; }
        public string LGATU { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CACAIXA> CACAIXA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTOS> PAGAMENTOS { get; set; }
        //public virtual USUARIO USUARIO { get; set; }
    }
}
