//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RESPCLI
    {
        public int Id { get; protected set; }
        public int SQMATRIC { get; set; }
        public int CDUOP { get; set; }
        public string NUCPF { get; set; }
        public System.DateTime DTATU { get; set; }
        public System.TimeSpan HRATU { get; set; }
        public string LGATU { get; set; }

        public virtual RESPONSAVEIS RESPONSAVEIS { get; set; }
        //public virtual CLIENTELA CLIENTELA { get; set; }
    }
}
