//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagamentoApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class USUARIO
    {
        public int Id { get; protected set; }
        public int CDPESSOA { get; set; }
        public string NMLOGIN { get; set; }
        public string NMSENHA { get; set; }
        public short VBATIVO { get; set; }
        public Nullable<System.DateTime> DTSENHAEXP { get; set; }
        public short VBSENHAEXP { get; set; }
        public string NMCHAVEAUTENT { get; set; }
        public string IDUSUARIO { get; set; }
        public string NMNICK { get; set; }
        public short VBACESSAPORTAL { get; set; }

        public virtual PESSOA PESSOA { get; set; }
    }
}
